# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation. 

name: Upload Python Package

on:
  workflow_run:
    workflows: ["Python Tests"]
    types:
      - completed # Only run, when the tests workflow Python Tests is completed
  push:
    branches:
      - main
    paths:
      - 'Python_BNumMet/VERSION' # Only trigger, when the version file is changed 
    


permissions: # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
  contents: read

jobs:
  deploy: # https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run, if the tests succeeded 

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        cd "Python_BNumMet"
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: |
        cd "Python_BNumMet" 
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        packages-dir: Python_BNumMet/dist/

      
